language: java
jdk:
- openjdk8

branches:
  only:
  - master

# Travis CI 서버의 Home
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: mjq-deploy # 6-3-3에서 생성한 S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: choish1919/mjq #Github 주소
    branch: master

# CI 실행 완료시 메일로 알람
#notifications:
#  email:
#    recipients:
#    - xxx@gmail.com