spring:
  profiles:
    active: set1 # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# 운영 DB
---
spring:
  profiles: real-db
  datasource:
    url: jdbc:mariadb://mjqdb.cltkdf16bdne.ap-northeast-2.rds.amazonaws.com:3306/mjqdb
    username: choish1919
    password: mjqislab235711
    driver-class-name: org.mariadb.jdbc.Driver

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db